### PR TITLE
Case update finalizer

### PR DESCRIPTION
**Pull request by apereverzin**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/BPS-1074

### Change description ###
Refactoring CcdCaseUpdater - extracted CaseUpdateFinalizer, updated CcdCaseUpdaterTest and added CaseUpdateFinalizerTest.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by lgonczar** [comment]
I disagree with this change. It adds sixth dependency, which submits an event to CCD, while the original class still starts the event directly. So now both talk to CCD at low level, the root class starting the event and the dependency completing it.

**Comment by doncem** [comment]
> I disagree with this change.

i think team is not on a ball with this. ticket has been moved out and more brain melting investigation is due to come

**Comment by apereverzin** [comment]
Sorry @doncem I should have close this PR

**Comment by apereverzin** [comment]
Needs more thinking

**Pull request closed without merging**
