### PR TITLE
[DO NOT MERGE] BPS-416 Date fields values without milliseconds

### PR DESCRIPTION
**Pull request by aliveni**
Run functional tests to check if CCD creates Exception Record / add evidence to the case with Date format changes (in bulk-scan-processor PR https://github.com/hmcts/bulk-scan-processor/pull/466 )

### CODE REVIEW

**Comment by lgonczar** [comment]
Why do we want to remove milliseconds from those dates? If we accept them with milliseconds, it seems to make most sense to represent them like that in the response.

**Comment by aliveni** [comment]
> Why do we want to remove milliseconds from those dates? If we accept them with milliseconds, it seems to make most sense to represent them like that in the message. Otherwise we lose some information.

@lgonczar I don't want to remove milliseconds from the test data. I just want to run functional tests with the changes made in https://github.com/hmcts/bulk-scan-processor/pull/466
To verify if this date format is causing any issues in CCD.

If the metadata have date fields with time values as zeros eg: `1970-01-01T00:00:00.000Z`, `Instant/LocalDateTime` classes are ignoring the milliseconds part and convert it to "1970-01-01T00:00:00Z". 
It works same as before for date fields with non-zero time values eg: `2018-06-23T02:10:30.123Z`

If this can not agreed, we should probably keep it as Timestamp. (unless there is any other way representing the date values with milliseconds precision)

**Comment by aliveni** [comment]
> Maybe we should configure Instant serialisation in the processor to keep the full `... .SSS'Z` format instead?

Sure, I'll try and update bulk-scan-processor PR

**Comment by doncem** [comment]
not sure why such a hassle for tiny thing like passing around milliseconds. if it is strictly defined in parsers then yes - absolutely needed. on the other hand, tests will be in place and break the build.

it is normal to interpret time as is. object has the knowledge that "if i'm missing milliseconds - i will assume it's 0"

furthermore, iirc ccd also has `LocalDateTime`s so any requests will be interpreted accordingly and properly. it has been tested long time ago. the only thing one should be aware of is microseconds - there's an issue parsing milliseconds bit out of microseconds string signature

in any case, i understand your point of view as well

**Comment by lgonczar** [comment]
> not sure why such a hassle for tiny thing like passing around milliseconds
> ...

My point is that if we require milliseconds on the input then we should pass them to CCD, as well, and test data should reflect that.

**Comment by aliveni** [comment]
> > not sure why such a hassle for tiny thing like passing around milliseconds
> > ...
> 
> My point is that if we require milliseconds on the input (metadata file) then we should pass them to CCD, as well, and test data should reflect that.

We do pass milliseconds to the CCD if they are not zero in the input metadata file.

**Pull request closed without merging**
